### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by khushalsonawat** [PaulCCCCCCH/Multimodal-Categorization-of-Crisis-Events-in-Social-Media#1]
The requirements mentioned in the files are conflicting. For instance, torchtext requires Pytorch 1.10.0, but torchvision requires 1.9.1. Similar conflicts are rising with numpy package versions. Any help is appreciated
Thanks in advance :)

**Comment by PaulCCCCCCH** [comment]
Thanks for asking!
The `requirements.txt` is auto-generated by `pipreqs` so it could be inaccurate. Sorry about this.

I think you can ignore the `requirements.txt` and rely on `pip` or `conda` to resolve the versions for you.

You may follow the instructions to get the latest pytorch here `https://pytorch.org/`, then install other libraries later.

e.g.
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
pip install imageio nltk Pillow scikit-learn tqdm transformers
```
