### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by khushalsonawat** [PaulCCCCCCH/Multimodal-Categorization-of-Crisis-Events-in-Social-Media#2]
Whenever I run `python3 main.py` I get this error
`File "main.py", line 52, in <module>
    raise NotImplemented
TypeError: exceptions must derive from BaseException`

I tried commenting out the `raise NotImplemented` line, but that sets the TASK variable equals to `None`. Are there any additional parameters that must be passed to successfully run the code for the first time?

**Comment by PaulCCCCCCH** [comment]
Hi, thanks for the issue.

Yes, you need to pass in a few arguments. '--task' is actually required.

You can see a list of arguments and help information in 'args.py'. Alternatively, see 'train.sh' for example arguments.

**Comment by ksonawat007** [comment]
Are there any other points that must be taken care of while running the code? If yes, please provide them.
Because I ran into this `FileNotFoundError: [Errno 2] No such file or directory: './datasets/CrisisMMD_v2.0/crisismmd_datasplit_all/task_informative_text_img_train.tsv'`

**Comment by PaulCCCCCCH** [comment]
Hi, can you run the code now? I'll close the issue soon if the problem has been resolved.
